# Site settings
title: Adam Noack
email: adamnoack1@gmail.com
url: https://a1noack.github.io
description: "Data scientist"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Adam Noack

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/adam-noack-2511a199/
  - title: github
    url: https://github.com/a1noack
  - title: stack-overflow
    url: https://stackoverflow.com/users/5541068/adam-noack
  - title: facebook
    url: https://www.facebook.com/adam.noack.94

# Build settings
markdown: kramdown
permalink: pretty
